---
title: "TTT stats from March 2021 until November 2021"
author: "Christopher Spartz"
date: "10/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(readxl)
pstats <- read_excel('TTTStatsTag.xlsx', sheet='PlayerStats')
tpartners <- read_excel('TTTStatsTag.xlsx', sheet='TraitorPartners')
dequip <- read_excel('TTTStatsTag.xlsx', sheet='DetectiveEquipment')
tequip <- read_excel('TTTStatsTag.xlsx', sheet='TraitorEquipment')
```
```{r, include=FALSE}
pstats$Player_Name <- as.factor(pstats$Player_Name)
pstatsClean <- pstats %>% pivot_longer(
  !c('Player_Name'),
  names_to="stat",
  values_to="count",
  values_drop_na = TRUE
)
```
```{r, include=FALSE}
tpartners$Player_Name <- as.factor(tpartners$Player_Name)
tpartnersClean <- tpartners %>% pivot_longer(
  !c('Player_Name'),
  names_to="stat",
  values_to="count",
  values_drop_na = TRUE
)
```
```{r, include=FALSE}
dequip$Player_Name <- as.factor(dequip$Player_Name)
dequipClean <- dequip %>% pivot_longer(
  !c('Player_Name'),
  names_to="stat",
  values_to="count",
  values_drop_na = TRUE
)
```
```{r, include=FALSE}
tequip$Player_Name <- as.factor(tequip$Player_Name)
tequipClean <- tequip %>% pivot_longer(
  !c('Player_Name'),
  names_to="stat",
  values_to="count",
  values_drop_na = TRUE
)
```


```{r, include=FALSE}
overallStatP <- pstatsClean %>% group_by(stat) %>% summarise(overall = sum(count))
overallStatTP <- tpartnersClean %>% group_by(stat) %>% summarise(overall = sum(count))
overallStatD <- dequipClean %>% group_by(stat) %>% summarise(overall = sum(count))
```


This Graph here shows off the total rounds played of each player
```{r Rounds}
ggplot(pstats, aes(y=TotalRoundsPlayed,x=Player_Name, fill=Player_Name)) + geom_bar(stat = "Identity") + geom_text(aes(label=TotalRoundsPlayed), vjust=1.6, color="white", size=3.5) + ggtitle("Total Rounds Played") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
```

```{r Overall-Stats, include=FALSE}
overallPStats <- read_excel('mydata.xlsx')
avgWin <- overallPStats %>% pivot_wider(names_from = stat,values_from = overall) %>% group_by(role) %>% summarise(winPercent=Wins/Rounds)
```

```{r Stats-Graph}
overallPStats %>% filter(stat=="Rounds") %>% ggplot(aes(x=role,y=overall,fill=role))+geom_bar(stat = "Identity")  + geom_text(aes(label=overall), vjust=1.6, color="black", size=3.5) + ggtitle("Rounds played as each role")
overallPStats %>% filter(stat=="Rounds" & role!="Innocent") %>% ggplot(aes(x="",y=overall/4715,fill=role)) + 
  geom_bar(stat="identity", width=1,color="white") +
  coord_polar("y", start=0) +
  theme_void()
avgWin %>% ggplot(aes(x=role,y=winPercent,fill=role))+geom_bar(stat = "Identity")+geom_text(aes(label=sprintf("%0.2f", round(winPercent, digits = 2))), vjust=1.6, color="black", size=3.5)
```



```{r Traitor}
ggplot(pstats,aes(x=TraitorWins, y=TraitorRounds, fill=Player_Name)) + geom_point() + ggtitle("Traitor Rounds vs. Traitor wins") +
  geom_label_repel(aes(label = Player_Name),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50') +
  theme_classic()

pstats %>% group_by(Player_Name,TraitorRounds,TraitorWins) %>% 
  summarise(winPercent=TraitorWins/TraitorRounds) %>%
  arrange(desc(winPercent))
```
```{r Traitor-Percent}
pstats %>% group_by(Player_Name) %>% summarise(percentPlayed=TraitorRounds/TotalRoundsPlayed) %>% 
  ggplot(aes(y=percentPlayed,x=Player_Name,fill=Player_Name)) + geom_bar(stat = "Identity") + ggtitle("Percent of rounds played as traitor") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+geom_text(aes(label=sprintf("%0.2f", round(percentPlayed, digits = 2))), vjust=1.6, color="black", size=3.5)
```

```{r Innocent}
ggplot(pstats,aes(x=InnocentWins, y=InnocentRounds, fill=Player_Name)) + geom_point() + ggtitle("Innocent Rounds vs. Innocent wins") +
  geom_label_repel(aes(label = Player_Name),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50') +
  theme_classic()

pstats %>% group_by(Player_Name,InnocentRounds,InnocentWins) %>% 
  summarise(winPercent=InnocentWins/InnocentRounds) %>%
  arrange(desc(winPercent))
```
```{r Innocent-Percent}
pstats %>% group_by(Player_Name) %>% summarise(percentPlayed=InnocentRounds/TotalRoundsPlayed) %>% 
  ggplot(aes(y=percentPlayed,x=Player_Name,fill=Player_Name)) + geom_bar(stat = "Identity") + ggtitle("Percent of rounds played as innocent") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+geom_text(aes(label=sprintf("%0.2f", round(percentPlayed, digits = 2))), vjust=1.6, color="black", size=3.5)
```


```{r Detective}
ggplot(pstats,aes(x=DetectiveWins, y=DetectiveRounds, fill=Player_Name)) + geom_point() + ggtitle("Detective Rounds vs. Detective wins") +
  geom_label_repel(aes(label = Player_Name),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50') +
  theme_classic()

pstats %>% group_by(Player_Name,DetectiveRounds,DetectiveWins) %>% 
  summarise(winPercent=DetectiveWins/DetectiveRounds) %>%
  arrange(desc(winPercent))
```
```{r Detective-Percent}
pstats %>% group_by(Player_Name) %>% summarise(percentPlayed=DetectiveRounds/TotalRoundsPlayed) %>% 
  ggplot(aes(y=percentPlayed,x=Player_Name,fill=Player_Name)) + geom_bar(stat = "Identity") + ggtitle("Percent of rounds played as detective") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+geom_text(aes(label=sprintf("%0.2f", round(percentPlayed, digits = 2))), vjust=1.6, color="black", size=3.5)
```

```{r Zombie}
ggplot(pstats,aes(x=Zombiewins, y=ZombieRounds, fill=Player_Name)) + geom_point() + ggtitle("Zombie Rounds vs. Zombie wins") +
  geom_label_repel(aes(label = Player_Name),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50') +
  theme_classic()

pstats %>% group_by(Player_Name,Zombiewins,ZombieRounds) %>% 
  summarise(winPercent=Zombiewins/ZombieRounds) %>%
  arrange(desc(winPercent))
```
```{r Zombie-Percent}
pstats %>% group_by(Player_Name) %>% summarise(percentPlayed=ZombieRounds/TotalRoundsPlayed) %>% 
  ggplot(aes(y=percentPlayed,x=Player_Name,fill=Player_Name)) + geom_bar(stat = "Identity") + ggtitle("Percent of rounds played as zombie") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+geom_text(aes(label=sprintf("%0.2f", round(percentPlayed, digits = 2))), vjust=1.6, color="black", size=3.5)
```

```{r Hypnotist}
ggplot(pstats,aes(x=HypnotistWins, y=HypnotistRounds, fill=Player_Name)) + geom_point() + ggtitle("Hypnotist Rounds vs. Hypnotist wins") +
  geom_label_repel(aes(label = Player_Name),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50') +
  theme_classic()

pstats %>% group_by(Player_Name,HypnotistWins,HypnotistRounds) %>% 
  summarise(winPercent=HypnotistWins/HypnotistRounds) %>%
  arrange(desc(winPercent))
```
```{r Hypnotist-Percent}
pstats %>% group_by(Player_Name) %>% summarise(percentPlayed=HypnotistRounds/TotalRoundsPlayed) %>% 
  ggplot(aes(y=percentPlayed,x=Player_Name,fill=Player_Name)) + geom_bar(stat = "Identity") + ggtitle("Percent of rounds played as hypnotist") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+geom_text(aes(label=sprintf("%0.2f", round(percentPlayed, digits = 2))), vjust=1.6, color="black", size=3.5)
```

```{r CrookedCop}
ggplot(pstats,aes(x=Player_Name, y=CrookedCop, fill=Player_Name)) + geom_bar(stat="identity") + geom_text(aes(label=CrookedCop), vjust=1.6, color="white", size=3.5) + ggtitle("Amount of Innocents killed as detective") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
pstats %>% group_by(Player_Name, DetectiveRounds, CrookedCop) %>% 
  summarise(Crookedeness=CrookedCop/DetectiveRounds) %>%
  arrange(desc(Crookedeness))
```

```{r TriggerHappy}
ggplot(pstats,aes(x=Player_Name, y=TriggerHappyInnocent, fill=Player_Name)) + geom_bar(stat="identity") + geom_text(aes(label=TriggerHappyInnocent), vjust=1.6, color="white", size=3.5) + ggtitle("Amount of Innocents killed as an Innocent") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
pstats %>% group_by(Player_Name, InnocentRounds, TriggerHappyInnocent) %>% 
  summarise(Shootyness=TriggerHappyInnocent/InnocentRounds) %>%
  arrange(desc(Shootyness))
```

```{r Killed-First}
ggplot(pstats,aes(x=Player_Name,y=KilledFirst,fill=Player_Name)) + geom_bar(stat = "Identity")  + geom_text(aes(label=KilledFirst), vjust=1.6, color="Blue", size=3.5) + ggtitle("Amount of times killed first") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

ggplot(pstats, aes(x=Player_Name, y=KilledFirst/TotalRoundsPlayed, fill=Player_Name)) + 
  geom_bar(stat="identity") + ggtitle("Percentage of times killed first") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+geom_text(aes(label=sprintf("%0.2f", round(KilledFirst/TotalRoundsPlayed, digits = 2))), vjust=1.6, color="black", size=3.5)
```


```{r Ledges}
ggplot(pstats,aes(x=Player_Name,y=TotalFallDamage, fill=Player_Name)) + geom_bar(stat = "Identity")  + geom_text(aes(label=TotalFallDamage), vjust=1.6, color="Blue", size=3.5) + ggtitle("People least safe near ledges") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
```


```{r DEBought}
dequipClean %>% group_by(stat) %>% summarise(overallTimesBought = sum(count)) %>%
  ggplot(aes(x=stat,y=overallTimesBought)) + geom_bar(stat="Identity") + geom_text(aes(label=overallTimesBought), vjust=1.6, color="Red", size=2.5) + ggtitle("Times each detective equipment was bought") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
dequipClean %>% group_by(stat) %>% summarise(percentBought=sum(count)/1172) %>% arrange(desc(percentBought))
```

```{r MostBasicUser}
dequipClean %>% filter(count>0) %>% group_by(Player_Name, stat) %>% summarise(equipBought=n()) %>% 
  ggplot(aes(x=Player_Name,y=equipBought, fill=Player_Name)) + geom_bar(stat = "Identity")  +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) + 
  ggtitle("Number of different detective equipment bought")

```

```{r Top5-Detective}
dequipClean  %>% filter(Player_Name=="Amazingbro17") %>% 
  slice_max(count,n=5)
dequipClean  %>% filter(Player_Name=="FunLiberal") %>% 
  slice_max(count,n=5)
dequipClean  %>% filter(Player_Name=="ghostNINJA-72") %>% 
  slice_max(count,n=5)
dequipClean  %>% filter(Player_Name=="Jeff_the_Shark") %>% 
  slice_max(count,n=5)
dequipClean  %>% filter(Player_Name=="King Nuggets") %>% 
  slice_max(count,n=5)
dequipClean  %>% filter(Player_Name=="MrBoy") %>% 
  slice_max(count,n=5)
dequipClean  %>% filter(Player_Name=="nuzzels") %>% 
  slice_max(count,n=5)
dequipClean  %>% filter(Player_Name=="silentscout9909") %>% 
  slice_max(count,n=5)
dequipClean  %>% filter(Player_Name=="TARTARI") %>% 
  slice_max(count,n=5)
dequipClean  %>% filter(Player_Name=="TheMathGeek_314") %>% 
  slice_max(count,n=5)
```




```{r Detective-Equipment, fig.height=10, fig.width=12}
dequipClean %>% ggplot(aes(x=Player_Name,y=count, fill=Player_Name)) + geom_bar(stat = "Identity") + facet_wrap(~stat, ncol=5, scales = "free_y") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
```


```{r TEBought, fig.height=10, fig.width=12}
tequipClean %>% group_by(stat) %>% summarise(overallTimesBought = sum(count)) %>%
  ggplot(aes(x=stat,y=overallTimesBought)) + geom_bar(stat="Identity") + geom_text(aes(label=overallTimesBought), vjust=1.6, color="Red", size=2.5) + ggtitle("Times each traitor equipment was bought") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
tequipClean %>% group_by(stat) %>% summarise(percentBought=sum(count)/1172) %>% arrange(desc(percentBought))
```
```{r MostBasicTraitor}
tequipClean %>% filter(count>0) %>% group_by(Player_Name, stat) %>% summarise(equipBought=n()) %>% 
  ggplot(aes(x=Player_Name,y=equipBought, fill=Player_Name)) + geom_bar(stat = "Identity")  +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) + 
  ggtitle("Number of different traitor equipment bought")

```

```{r Top5-Traitor}
tequipClean  %>% filter(Player_Name=="Amazingbro17") %>% 
  slice_max(count,n=5)
tequipClean  %>% filter(Player_Name=="FunLiberal") %>% 
  slice_max(count,n=5)
tequipClean  %>% filter(Player_Name=="ghostNINJA-72") %>% 
  slice_max(count,n=5)
tequipClean  %>% filter(Player_Name=="Jeff_the_Shark") %>% 
  slice_max(count,n=5)
tequipClean  %>% filter(Player_Name=="King Nuggets") %>% 
  slice_max(count,n=5)
tequipClean  %>% filter(Player_Name=="MrBoy") %>% 
  slice_max(count,n=5)
tequipClean  %>% filter(Player_Name=="nuzzels") %>% 
  slice_max(count,n=5)
tequipClean  %>% filter(Player_Name=="silentscout9909") %>% 
  slice_max(count,n=5)
tequipClean  %>% filter(Player_Name=="TARTARI") %>% 
  slice_max(count,n=5)
tequipClean  %>% filter(Player_Name=="TheMathGeek_314") %>% 
  slice_max(count,n=5)
```



```{r Traitor-Equipment, fig.height=18, fig.width=15}
tequipClean %>% ggplot(aes(x=Player_Name,y=count, fill=Player_Name)) + geom_bar(stat = "Identity") + facet_wrap(~stat, ncol=6, scales = "free_y") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
```


